# Generated by Django 5.2.11 on 2026-02-15 17:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=150)),
                ('company_logo', models.CharField(max_length=255)),
                ('company_address', models.CharField(max_length=255)),
                ('tin_number', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('product_name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('starting_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('MOQ', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('user_title', models.CharField(choices=[('Admin', 'Admin'), ('Account Manager', 'Account Manager'), ('Production', 'Production'), ('Sales Officer', 'Sales Officer'), ('Marketing Officer', 'Marketing Officer'), ('Graphic Designer', 'Graphic Designer')], max_length=50)),
                ('user_role', models.CharField(choices=[('Admin', 'Admin'), ('Account Manager', 'Account Manager'), ('Officer', 'Officer'), ('Other', 'Other')], default='Other', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.CharField(max_length=100)),
                ('customer_phone_number', models.CharField(max_length=20)),
                ('messenger', models.CharField(blank=True, max_length=100, null=True)),
                ('viber', models.CharField(blank=True, max_length=15, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BVTCApp.company')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_ID', models.AutoField(primary_key=True, serialize=False)),
                ('mode_of_payment', models.CharField(choices=[('Metrobank Fund Transfer', 'Metrobank Fund Transfer'), ('BPI Bank Transfer', 'BPI Bank Transfer'), ('GCash Payment', 'GCash Payment')], max_length=50)),
                ('payment_terms', models.CharField(choices=[('Partial', 'Partial'), ('Full', 'Full')], max_length=20)),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('initial_total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('start_of_production', models.DateField(default=django.utils.timezone.now)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('lead_time', models.PositiveIntegerField(default=1)),
                ('transaction_platform', models.CharField(max_length=50)),
                ('link_to_logo', models.CharField(max_length=500)),
                ('packing_instructions', models.TextField(blank=True, null=True)),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved for Production', 'Approved for Production'), ('In Production', 'In Production'), ('Completed', 'Completed'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('freight_term', models.BooleanField(default=False)),
                ('delivery_fee', models.BooleanField(default=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, null=True)),
                ('stock_availability', models.CharField(choices=[('Available', 'Available'), ('Limited', 'Limited'), ('Out of Stock', 'Out of Stock')], default='Available', max_length=20)),
                ('customization_feasibility', models.CharField(max_length=100)),
                ('lead_time_feasibility', models.PositiveIntegerField(default=0)),
                ('actual_total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('Customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BVTCApp.customeraccount')),
            ],
        ),
        migrations.CreateModel(
            name='BillingStatement',
            fields=[
                ('billing_statement_id', models.AutoField(primary_key=True, serialize=False)),
                ('billing_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BVTCApp.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('customization', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BVTCApp.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BVTCApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_path', models.CharField(max_length=255)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('image_type', models.CharField(choices=[('Customer Provided', 'Customer Provided'), ('In-House', 'In-House'), ('Sample', 'Sample')], max_length=20)),
                ('image_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=15)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BVTCApp.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BVTCApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_color', models.CharField(max_length=100)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BVTCApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Image', models.CharField(max_length=255)),
                ('Product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BVTCApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingDetails',
            fields=[
                ('shipping_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_person', models.CharField(max_length=150)),
                ('contact_person_email', models.EmailField(max_length=100)),
                ('contact_person_number', models.CharField(max_length=20)),
                ('address_province', models.CharField(max_length=60)),
                ('address_city', models.CharField(max_length=60)),
                ('address_barangay', models.CharField(max_length=60)),
                ('address_line_1', models.CharField(max_length=100)),
                ('address_line_2', models.CharField(blank=True, max_length=100, null=True)),
                ('address_postal_code', models.IntegerField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BVTCApp.customeraccount')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='Shipping_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BVTCApp.shippingdetails'),
        ),
        migrations.AddField(
            model_name='order',
            name='User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BVTCApp.useraccount'),
        ),
    ]
