# Generated by Django 5.2.11 on 2026-02-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BVTCApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='Product_Image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
