# Generated by Django 5.2.11 on 2026-02-15 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BVTCApp', '0002_alter_productimage_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='customeraccount',
            options={'verbose_name_plural': 'Customer Accounts'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelOptions(
            name='productcolor',
            options={'verbose_name_plural': 'Product Colors'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterModelOptions(
            name='shippingdetails',
            options={'verbose_name_plural': 'Shipping Details'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Customer_ID',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Order_ID',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Shipping_ID',
            new_name='shipping_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='User_ID',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='Product_ID',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='Product_Image',
            new_name='product_image',
        ),
    ]
