# Generated by Django 6.0.2 on 2026-02-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BVTCApp', '0003_alter_company_options_alter_customeraccount_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingdetails',
            old_name='contact_person',
            new_name='contact_person_name',
        ),
        migrations.AddField(
            model_name='billingstatement',
            name='payment_status',
            field=models.CharField(choices=[('Acknowledged', 'Acknowledged'), ('Issued', 'Issued'), ('Paid', 'Paid')], default='Acknowledged', max_length=50),
        ),
        migrations.AddField(
            model_name='billingstatement',
            name='payment_term',
            field=models.CharField(choices=[('Partial-Initial', 'Partial-Initial'), ('Partial-Final', 'Partial-Final'), ('Full', 'Full')], default='Partial-Initial', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='actual_total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Under Feasibility', 'Under Feasibility'), ('Under Quotation', 'Under Quotation'), ('In Production', 'In Production'), ('Sampled', 'Sampled'), ('Packaged', 'Packaged'), ('In Transit', 'In Transit'), ('Under Validation', 'Under Validation'), ('Validated', 'Validated'), ('Sent to Customer', 'Sent to Customer'), ('Signed', 'Signed'), ('Issued', 'Issued')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='stock_availability',
            field=models.CharField(choices=[('Available', 'Available'), ('Limited', 'Limited'), ('Out of Stock', 'Out of Stock')], default='Available', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Company Profile', 'Company Profile'), ('Individual Items', 'Individual Items'), ('Gift Set', 'Gift Set'), ('Bag', 'Bag')], max_length=100),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user_title',
            field=models.CharField(choices=[('Account Manager', 'Account Manager'), ('Production', 'Production'), ('Sales Officer', 'Sales Officer'), ('Marketing Officer', 'Marketing Officer'), ('Graphic Designer', 'Graphic Designer')], max_length=50),
        ),
    ]
