# Generated by Django 6.0.2 on 2026-02-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BVTCApp', '0004_rename_contact_person_shippingdetails_contact_person_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_path',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='customization_feasibility',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='lead_time_feasibility',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='link_to_logo',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Under Feasibility', 'Under Feasibility'), ('Under Quotation', 'Under Quotation'), ('In Production', 'In Production'), ('Sampled', 'Sampled'), ('Packaged', 'Packaged'), ('In Transit', 'In Transit'), ('Under Validation', 'Under Validation'), ('Validated', 'Validated'), ('Sent to Customer', 'Sent to Customer'), ('Signed', 'Signed'), ('Issued', 'Issued')], default='Under Feasibility', max_length=50),
        ),
    ]
