# Generated by Django 6.0.2 on 2026-02-16 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BVTCApp', '0005_alter_company_company_logo_alter_image_image_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='link_to_logo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
