# Generated by Django 5.1.6 on 2026-04-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BVTCApp", "0006_alter_order_link_to_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Apparel", "Apparel"),
                    ("Awards & Recognition", "Awards & Recognition"),
                    ("Bag", "Bag"),
                    ("Coffee & Wine Item", "Coffee & Wine Item"),
                    ("Drinkware", "Drinkware"),
                    ("Eco Item", "Eco Item"),
                    ("Gadgets & Electronics", "Gadgets & Electronics"),
                    ("Individual Item", "Individual Item"),
                    ("Leather Item", "Leather Item"),
                    ("Office Item", "Office Item"),
                    ("Packaging Item", "Packaging Item"),
                    ("Wellness & Travel", "Wellness & Travel"),
                    ("Others", "Others"),
                ],
                default="others",
                max_length=100,
            ),
        ),
    ]
