# Generated by Django 5.1.6 on 2026-04-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BVTCApp", "0007_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="customeraccount",
            name="email_transaction",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customeraccount",
            name="messenger_transaction",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customeraccount",
            name="viber_transaction",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="courier",
            field=models.CharField(default="N/A", max_length=50),
        ),
    ]
