# Generated by Django 5.1.6 on 2026-04-29 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("BVTCApp", "0007_customeraccount_email_transaction_and_more"),
        ("BVTCApp", "0008_customeraccount_email_transaction_and_more"),
    ]

    operations = []
