# Generated by Django 6.0.2 on 2026-04-29 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BVTCApp', '0007_customeraccount_email_transaction_and_more'),
        ('BVTCApp', '0008_customeraccount_email_transaction_and_more'),
    ]

    operations = [
    ]
