# Generated by Django 5.2.11 on 2026-05-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BVTCApp', '0010_city_province_barangay_city_province'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='useraccount',
        #     name='user_title',
        # ),
        migrations.AlterField(
            model_name='image',
            name='image_path',
            field=models.ImageField(max_length=255, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customization_feasibility',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Under Feasibility', 'Under Feasibility'), ('Feasibility Report Sent', 'Feasibility Report Sent'), ('Under Quotation', 'Under Quotation'), ('In Production', 'In Production'), ('Sampled', 'Sampled'), ('Packaged', 'Packaged'), ('In Transit', 'In Transit'), ('Under Validation', 'Under Validation'), ('Validated', 'Validated'), ('Sent to Customer', 'Sent to Customer'), ('Signed', 'Signed'), ('Issued', 'Issued')], default='Under Feasibility', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='MOQ',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Apparel', 'Apparel'), ('Awards & Recognition', 'Awards & Recognition'), ('Bag', 'Bag'), ('Coffee & Wine Item', 'Coffee & Wine Item'), ('Drinkware', 'Drinkware'), ('Eco Item', 'Eco Item'), ('Gadgets & Electronics', 'Gadgets & Electronics'), ('Individual Item', 'Individual Item'), ('Leather Item', 'Leather Item'), ('Office Item', 'Office Item'), ('Packaging Item', 'Packaging Item'), ('Wellness & Travel', 'Wellness & Travel'), ('Others', 'Others')], default='Others', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user_role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Account Manager', 'Account Manager'), ('Officer', 'Officer'), ('Production', 'Production'), ('Graphic Designer', 'Graphic Designer'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
