# Generated by Django 5.2.11 on 2026-05-05 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BVTCApp', '0011_remove_useraccount_user_title_alter_image_image_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='customization',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BVTCApp.product'),
        ),
    ]
