# Generated by Django 5.2.11 on 2026-05-05 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BVTCApp', '0013_remove_useraccount_user_title'),
    ]

    operations = [
    ]
