# Generated by Django 5.2.11 on 2026-05-05 14:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BVTCApp', '0014_remove_useraccount_user_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_quoted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
